title: "The Archive"
description: "Physics, Code, Life, and Photography."
url: "https://onlyextreme.github.io" # 替换成你的
baseurl: "" 

# 核心设置
markdown: kramdown
permalink: /:year/:month/:day/:title/

# 启用数学公式支持
kramdown:
  math_engine: mathjax

# 排除不需要的文件
exclude: [README.md, Gemfile, Gemfile.lock]